[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:5500/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
