[build]
  command = "npm run build"
  publish = "dist/"
  functions = "functions/"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:5000/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = {Path=="/"}
  
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "https://friendly-selkie-e086b0.netlify.app/.netlify/functions/:splat"
  status = 200
