[build]
  command = "gulp build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "http://localhost:3000/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
