[build]
  command = "npm run build"
  publish = "dist/"
  functions = "functions/"

[[redirects]]
  from = "/.netlify/functions/:solat"
  to = "https://friendly-selkie-e086b0.netlify.app/.netlify/functions/:solat"
  status = 200
  force = true
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

